FA.JustBlog/Areas/Admin/Controllers/PostManagerController.cs
using FA.JustBlog.Core.Common;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repository.ImplementRepo;
using FA.JustBlog.Core.Repository.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("PostManager/{action}")]
    [Authorize(Roles =("Blog Owner,Contributor"))]
    public class PostManagerController : Controller
    {
        private IUnitOfWork uow;
        public PostManagerController(IUnitOfWork uow)
        {
            this.uow = uow;
        }
        // GET: PostManagerController
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var result = uow.PostRepository.GetAll().OrderByDescending(p => p.PostId).Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalRecord = uow.PostRepository.GetAll().Count();
            return View(result);

        }



        // GET: PostManagerController/Details/5
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                var post = uow.PostRepository.Find(id.Value);
                if (post != null)
                {
                    return View(post);
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult getLastedPost()
        {
            var rs = uow.PostRepository.GetLatestPost(5);
            return View(rs.ToList());
        }
        public ActionResult mostViewPost()
        {
            var rs = uow.PostRepository.GetMostViewedPost(5);
            return View(rs.ToList());
        }
        [Authorize(Roles = ("Blog Owner"))]
        public ActionResult getPostByPublished()
        {
            var rs = uow.PostRepository.GetPublisedPosts();
            return View(rs.ToList());
        }
        [Authorize(Roles = ("Blog Owner"))]
        public ActionResult getUnPublished()
        {
            var rs = uow.PostRepository.GetUnpublisedPosts();
            return View(rs.ToList());
        }

        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // GET: PostManagerController/Create
        public ActionResult Create()
        {
            var cate = uow.CategoryRepository.GetAll();
            var list = new List<SelectListItem>();
            foreach (var c in cate)
            {
                list.Add(new SelectListItem() { Value=c.CategoryId.ToString(),Text=c.Name});
            }
            ViewData["categories"] = list;
            //var rs = SeoUrlHepler.ToUrlSlug(post.Title);
            //post.UrlSlug = rs;
            //uow.PostRepository.Add(post);
            //return RedirectToAction("Index");
            return View();
        }
        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // POST: PostManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
           

            post.Modified = DateTime.Now;
            post.PostedOn = DateTime.Today;

            var rs = SeoUrlHepler.ToUrlSlug(post.Title);
            post.UrlSlug = rs;
           
            uow.PostRepository.Add(post);

            uow.SaveChange();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = ("Blog Owner,Contributor"))]
        //GET: PostManagerController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cate = uow.CategoryRepository.GetAll();
            var list = new List<SelectListItem>();
            foreach (var c in cate)
            {
                list.Add(new SelectListItem() { Value = c.CategoryId.ToString(), Text = c.Name });
            }
            ViewData["categories"] = list;

            var post = uow.PostRepository.Find(id.Value);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);

        }
        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // POST: PostManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            post.PostedOn = DateTime.Now;
            post.Modified = DateTime.Now;
            var rs = SeoUrlHepler.ToUrlSlug(post.Title);
            post.UrlSlug = rs;

            uow.PostRepository.Update(post);
            uow.SaveChange();

            return RedirectToAction("Index");
        }


        [Authorize(Roles = ("Blog Owner"))]
        // GET: PostManagerController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                uow.PostRepository.Delete(id.Value);
            }
            return RedirectToAction("Index");
        }

    }
}

FA.JustBlog/Areas/Admin/Views/PostManager/Create.cshtml
@model FA.JustBlog.Core.Models.Post

@{
    ViewData["Title"] = "Create";
    var list = ViewData["categories"] as List<SelectListItem>;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/Themes/ckeditor/ckeditor.js"></script>

<h1>Create</h1>

<h4>Post</h4>
<hr />
<form method="post" asp-controller="PostManager" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h4 class="text-dark">Create</h4>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="@Model.Title"></label>
            <input asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ShortDescription"></label>
            <textarea  asp-for="@Model.ShortDescription" rows="3" class="form-control">
                </textarea>
                <span asp-validation-for="@Model.ShortDescription" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="form-group">
                <label asp-for="PostContent" class="control-label"></label>
                @Html.TextAreaFor(Model => Model.PostContent, new {@id = "FullDescription",
                @class = "form-control" , @rows = "200"})
                @* <textarea asp-for="PostContent" class="form-control"></textarea>*@
                <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3">
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="CategoryId" class="control-label">Categories</label>
            <select asp-for="CategoryId" asp-items="list" class="form-control"></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ViewCount"></label>
            <input type="number" asp-for="@Model.ViewCount" rows="3" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.RateCount"></label>
            <input type="number" asp-for="@Model.RateCount" rows="3" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.TotalRate"></label>
            <input type="number" asp-for="@Model.TotalRate" rows="3" class="form-control" />
        </div>
       
        <button type="submit" class="btn btn-dark" style="width:150px">Create</button>
        <a asp-controller="PostManage" asp-action="Index" class="btn btn-outline-dark" style="width:150px">
            Back to list
        </a>
    </div>
</form>
@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="PostContent" class="control-label"></label>
                @Html.TextAreaFor(Model => Model.PostContent, new {@id = "FullDescription",
                @class = "form-control" , @rows = "200"})
                @* <textarea asp-for="PostContent" class="form-control"></textarea>*@
               @* <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" readonly />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PostedOn" class="control-label"></label>
                <input asp-for="PostedOn" class="form-control" readonly/>
                <span asp-validation-for="PostedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" readonly />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">  
                <label asp-for="CategoryId" class="control-label">Select Category</label>
                <select asp-for="CategoryId" asp-items="list" class="form-control"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ViewCount" class="control-label"></label>
                <input asp-for="ViewCount" class="form-control" />
                <span asp-validation-for="ViewCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RateCount" class="control-label"></label>
                <input asp-for="RateCount" class="form-control" />
                <span asp-validation-for="RateCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalRate" class="control-label"></label>
                <input asp-for="TotalRate" class="form-control" />
                <span asp-validation-for="TotalRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@
<script>CKEDITOR.replace("FullDescription");</script>

FA.JustBlog/Areas/Admin/Views/PostManager/Details.cshtml
@model FA.JustBlog.Core.Models.Post

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ViewCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RateCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RateCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalRate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalRate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PostId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FA.JustBlog/Areas/Admin/Views/PostManager/Edit.cshtml
@model FA.JustBlog.Core.Models.Post
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Edit";
    var list = ViewData["categories"] as List<SelectListItem>;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/Themes/ckeditor/ckeditor.js"></script>
<h1>Edit</h1>
<form method="post" asp-controller="PostManager" asp-action="Edit">
    <input asp-for="@Model.PostId" class="form-control" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h4 class="text-dark">Edit Post</h4>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="@Model.Title"></label>
            <input asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ShortDescription"></label>
            <textarea asp-for="@Model.ShortDescription" rows="3" class="form-control"></textarea>
            <span asp-validation-for="@Model.ShortDescription" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="form-group">
                <label asp-for="PostContent" class="control-label"></label>
                @Html.TextAreaFor(Model => Model.PostContent, new {@id = "FullDescription",
                @class = "form-control" , @rows = "200"})
                <textarea asp-for="PostContent" class="form-control"></textarea>
                <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3">
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ViewCount"></label>
            <input type="number" asp-for="@Model.ViewCount" rows="3" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.RateCount"></label>
            <input type="number" asp-for="@Model.RateCount" rows="3" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.TotalRate"></label>
            <input type="number" asp-for="@Model.TotalRate" rows="3" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="CategoryId" class="control-label">Categories</label>
            <select asp-for="CategoryId" asp-items="list" class="form-control"></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-dark" style="width:150px">Save</button>
        <a asp-controller="PostManage" asp-action="Index" class="btn btn-outline-dark" style="width:150px">
            Back to list
        </a>
</form>
<script>CKEDITOR.replace("FullDescription");</script>

FA.JustBlog/Areas/Admin/Views/PostManager/Index.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Kiểu dáng mặc định cho thẻ <a> */
    p a {
        position: relative; /* Đặt vị trí tương đối để có thể chồng chữ lên background */
        color: #333; /* Màu chữ */
        text-decoration: none; /* Loại bỏ gạch chân */
        padding: 10px 20px; /* Kích thước padding */
        border-radius: 5px; /* Bo viền */
        background-color: transparent; /* Màu nền trong suốt */
        border: 2px solid #333; /* Viền */
        transition: background-color 0.3s ease; /* Hiệu ứng chuyển đổi màu nền khi hover */
    }

        /* Hiệu ứng gradient khi hover */
        p a:hover::before {
            content: ""; /* Tạo một pseudo-element */
            position: absolute; /* Đặt vị trí tuyệt đối để chồng lên nền */
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(to bottom, rgba(51, 51, 51, 0.5), rgba(51, 51, 51, 0.5)); /* Gradient màu nền */
            border-radius: 5px; /* Bo viền */
        }

        /* Kiểu dáng chữ khi hover */
        p a:hover {
            color: #333; /* Màu chữ khi hover */
        }
</style>


<h1 style="color:green">List Post</h1>

<p>
    <a asp-action="Create" class="custom-link">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.PostContent)
            </th>*@
          @*  <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlSlug)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Published)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewCount)
            </th>
           @* <th>
                @Html.DisplayNameFor(model => model.RateCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
               @* <td id="readmore">
                    <span class="readmore__content">
                        @Html.DisplayFor(modelItem => item.PostContent)
                    </span>
                    <button class="readmore__toggle">
                        ...more
                    </button
                </td>*@
         @*   <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlSlug)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Published)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ViewCount)
            </td>
        @*    <td>
                @Html.DisplayFor(modelItem => item.RateCount)
            </td>*@
           @* <td>
                @Html.DisplayFor(modelItem => item.TotalRate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Desciption)
            </td>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.PostId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PostId">Details</a> |
                @*<a asp-action="Delete" asp-route-id="@item.PostId">Delete</a>*@
                    @Html.ActionLink("Delete", "Delete",new {  id=item.PostId },
                    new { onclick = "return confirm('Are U sure to Remove?');"})
            </td>
        </tr>
}
    </tbody>
</table>
<nav aria-label="Page navigation text-center" class="d-flex justify-content-center align-items-center">
    <ul class="pagination">
        @if (ViewBag.PageNumber > 1)
        {
            <li class="page-item">
                <a href="/PostManager/Index?page=1" class="page-link">First Page</a>
            </li>

        }

        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize); i++)
        {
            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                <a href="/PostManager/Index?page=@i" class="page-link">@i</a>
            </li>
        }

        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize))
        {
            <li class="page-item">
                <a href="/PostManager/Index?page=@Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize)" class="page-link">Last Page</a>
            </li>
        }
    </ul>
</nav>

FA.JustBlog/Areas/Admin/Views/PostManager/getLastedPost.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>

@{
    ViewData["Title"] = "getLastedPost";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="color:red">5 Lasted Post</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlSlug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Published)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RateCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalRate)
            </th>
         @*   <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
                <td id="readmore">
                    <span class="readmore__content">
                        @Html.DisplayFor(modelItem => item.PostContent)
                    </span>
                    <button class="readmore__toggle">
                        ...more
                    </button>
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlSlug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Published)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ViewCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RateCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalRate)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Category.Desciption)
            </td>*@
        </tr>
}
    </tbody>
</table>

FA.JustBlog/Areas/Admin/Views/PostManager/getPostByPublished.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>

@{
    ViewData["Title"] = "getPostByPublished";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="color:red">Post Published</h2>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlSlug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Published)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RateCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalRate)
            </th>
            @*    <th>
            @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShortDescription)
                </td>
                <td id="readmore">
                    <span class="readmore__content">
                        @Html.DisplayFor(modelItem => item.PostContent)
                    </span>
                    <button class="readmore__toggle">
                        ...more
                    </button>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UrlSlug)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Published)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modified)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ViewCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RateCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalRate)
                </td>
                @* <td>
            @Html.DisplayFor(modelItem => item.Category.Desciption)
            </td>
            <td>
            <a asp-action="Edit" asp-route-id="@item.PostId">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.PostId">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.PostId">Delete</a>
            </td>*@
            </tr>
        }
    </tbody>
</table>
@*<nav aria-label="Page navigation text-center" class="d-flex justify-content-center align-items-center">
    <ul class="pagination">
        @if (ViewBag.PageNumber > 1)
        {
            <li class="page-item">
                <a href="/PostManager/Index?page=1" class="page-link">First Page</a>
            </li>

        }
        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize); i++)
        {
            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                <a href="/PostManager/Index?page=@i" class="page-link">@i</a>
            </li>
        }

        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize))
        {
            <li class="page-item">
                <a href="/PostManager/Index?page=@Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize)" class="page-link">Last Page</a>
            </li>
        }
    </ul>
</nav>*@