FA.JustBlog/Areas/Admin/Controllers/CategoryManagerController.cs
using FA.JustBlog.Core.Common;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repository.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using System.Data;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("CategoryManager/{action}")]
    [Authorize(Roles = ("Blog Owner,Contributor"))]
    public class CategoryManagerController : Controller
    {
        private IUnitOfWork uow;
        public CategoryManagerController(IUnitOfWork uow)
        {
            this.uow = uow;
        }
        // GET: CategoryManagerController
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var result = uow.CategoryRepository.GetAll().OrderByDescending(p => p.CategoryId).Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalRecord = uow.CategoryRepository.GetAll().Count();
            return View(result);
        }

        // GET: CategoryManagerController/Details/5
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                var post = uow.CategoryRepository.Find(id.Value);
                if (post != null)
                {
                    return View(post);
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // GET: CategoryManagerController/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // POST: CategoryManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category categories)
        {
            var rs = SeoUrlHepler.ToUrlSlug(categories.Name);
            categories.UrlSlug = rs;
            uow.CategoryRepository.Add(categories);
            uow.SaveChange();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // GET: CategoryManagerController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = uow.CategoryRepository.Find(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [Authorize(Roles = ("Blog Owner,Contributor"))]
        // POST: CategoryManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            
            var rs = SeoUrlHepler.ToUrlSlug(category.Name);
            category.UrlSlug = rs;



            uow.CategoryRepository.Update(category);
            uow.SaveChange();
    
            return RedirectToAction("Index");
        }
        [Authorize(Roles = ("Blog Owner"))]
        // GET: CategoryManagerController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                uow.CategoryRepository.Delete(id.Value);
            }
            return RedirectToAction("Index");
        }

        // POST: CategoryManagerController/Delete/5
        [Authorize(Roles = ("Blog Owner"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FA.JustBlog/Areas/Admin/Views/CategoryManager/Create.cshtml
@model FA.JustBlog.Core.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="color:red;">Create new Category</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Desciption" class="control-label"></label>
                <input asp-for="Desciption" class="form-control" />
                <span asp-validation-for="Desciption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FA.JustBlog/Areas/Admin/Views/CategoryManager/Details.cshtml
@model FA.JustBlog.Core.Models.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>
@*

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <div class="mb-3">
            <lable asp-for="@Model.Name"></lable>
            <input asp-for="@Model.Name" class="form-control" disabled></input>
        </div>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desciption)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desciption)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CategoryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@
<form method="post" asp-controller="CategoryManager" asp-action="Details">
    <input asp-for="@Model.CategoryId" class="form-control" hidden />

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h4 class="text-dark">Details</h4>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="@Model.Name"></label>
            <input asp-for="@Model.Name" class="form-control" disabled />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Desciption"></label>
            <input asp-for="@Model.Desciption" rows="3" class="form-control" disabled />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.UrlSlug"></label>
            <input asp-for="@Model.UrlSlug" rows="3" class="form-control" disabled />
        </div>

        <a asp-controller="CategoryManager" asp-action="Index" class="btn btn-outline-dark">
            Back to list
        </a>
    </div>
</form>

FA.JustBlog/Areas/Admin/Views/CategoryManager/Edit.cshtml
@model FA.JustBlog.Core.Models.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Desciption" class="control-label"></label>
                <input asp-for="Desciption" class="form-control" />
                <span asp-validation-for="Desciption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FA.JustBlog/Areas/Admin/Views/CategoryManager/Index.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="color:red;">List Category</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlSlug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desciption)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlSlug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desciption)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CategoryId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CategoryId">Details</a> |
                    @Html.ActionLink("Delete", "Delete",new {  id=item.CategoryId },
                new { onclick = "return confirm('Are U sure to Remove?');"})
            </td>
        </tr>
}
    </tbody>
</table>

<nav aria-label="Page navigation text-center" class="d-flex justify-content-center align-items-center">
    <ul class="pagination">
        @if (ViewBag.PageNumber > 1)
        {
            <li class="page-item">
                <a href="/CategoryManager/Index?page=1" class="page-link">First Page</a>
            </li>

        }

        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize); i++)
        {
            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                <a href="/CategoryManager/Index?page=@i" class="page-link">@i</a>
            </li>
        }

        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize))
        {
            <li class="page-item">
                <a href="/CategoryManager/Index?page=@Math.Ceiling((decimal)ViewBag.TotalRecord / ViewBag.PageSize)" class="page-link">Last Page</a>
            </li>
        }
    </ul>
</nav>